[general]
root_path = "~/.asr"


[models]
[models.llama]
[models.llama.general]
version = ""
download_path = ""
download_version = ""
size = ""

[models.llama.config]
n_vocab       = 0


[models.whisper]
n_vocab       = ""
n_audio_ctx   = 1500
n_audio_state = 384
n_audio_head  = 6
n_audio_layer = 4
n_text_ctx    = 448
n_text_state  = 384
n_text_head   = 6
n_text_layer  = 4
n_mels        = 80
f16           = 1
type          = 1
