[init_config_defaults]
n_vocab       = 51864
n_audio_ctx   = 1500
n_audio_state = 384
n_audio_head  = 6
n_audio_layer = 4
n_text_ctx    = 448
n_text_state  = 384
n_text_head   = 6
n_text_layer  = 4
n_mels        = 80
f16           = 1
type          = 1
